### PR TITLE
gpx files for elevation profile / course maps

### PR DESCRIPTION
**Pull request by ethanjped**

### CODE REVIEW

**Comment by ethanjped** [comment]
I am worried about the potential size of the data and how it will affect performance. It seems to already be slow with just our bar chart table. For now ~20mb of gpx data is fine but this is only for like 15 races

**Comment by jacksondean17** [comment]
I think its only slow because it has to update 1600 cols on every sort. This is why I want to implement the grouping feature.

**Comment by jacksondean17** [comment]
We should also do some tests to see what the slow part of loading is. Either reading the files, processing the data, or drawing the html.
If its reading or processing, we could preprocess the data into a more concise format like we discussed before.

**Comment by jacksondean17** [comment]
> I am worried about the potential size of the data and how it will affect performance. It seems to already be slow with just our bar chart table. For now ~20mb of gpx data is fine but this is only for like 15 races

We could do some processing to make the files lower resolution. We probably dont need every data point if we're just drawing the elevation profiles.

**Pull request merged**
